{
    ["actionbar"] = {
        ["bar1"] = {
            ["buttonSize"] = 47,
            ["buttonSpacing"] = 5,
            ["countFont"] = "Expressway",
            ["countFontOutline"] = "NONE",
            ["countFontSize"] = 11,
            ["hotkeyFont"] = "Expressway",
            ["hotkeyFontOutline"] = "NONE",
            ["hotkeyFontSize"] = 11,
            ["hotkeyTextXOffset"] = -2,
            ["macroFont"] = "Expressway",
            ["macroFontOutline"] = "NONE",
            ["macroFontSize"] = 11,
        },
        ["bar10"] = {
            ["countFont"] = "Expressway",
            ["countFontOutline"] = "NONE",
            ["countFontSize"] = 11,
            ["hotkeyFont"] = "Expressway",
            ["hotkeyFontOutline"] = "NONE",
            ["hotkeyFontSize"] = 11,
            ["hotkeyTextXOffset"] = -2,
            ["macroFont"] = "Expressway",
            ["macroFontOutline"] = "NONE",
            ["macroFontSize"] = 11,
        },
        ["bar2"] = {
            ["countFont"] = "Expressway",
            ["countFontOutline"] = "NONE",
            ["countFontSize"] = 11,
            ["hotkeyFont"] = "Expressway",
            ["hotkeyFontOutline"] = "NONE",
            ["hotkeyFontSize"] = 11,
            ["hotkeyTextXOffset"] = -2,
            ["macroFont"] = "Expressway",
            ["macroFontOutline"] = "NONE",
            ["macroFontSize"] = 11,
        },
        ["bar3"] = {
            ["buttons"] = 12,
            ["countFont"] = "Expressway",
            ["countFontOutline"] = "NONE",
            ["countFontSize"] = 11,
            ["enabled"] = false,
            ["hotkeyFont"] = "Expressway",
            ["hotkeyFontOutline"] = "NONE",
            ["hotkeyFontSize"] = 11,
            ["hotkeyTextXOffset"] = -2,
            ["macroFont"] = "Expressway",
            ["macroFontOutline"] = "NONE",
            ["macroFontSize"] = 11,
            ["showGrid"] = false,
        },
        ["bar4"] = {
            ["countFont"] = "Expressway",
            ["countFontOutline"] = "NONE",
            ["countFontSize"] = 11,
            ["enabled"] = false,
            ["hotkeyFont"] = "Expressway",
            ["hotkeyFontOutline"] = "NONE",
            ["hotkeyFontSize"] = 11,
            ["hotkeyTextXOffset"] = -2,
            ["macroFont"] = "Expressway",
            ["macroFontOutline"] = "NONE",
            ["macroFontSize"] = 11,
        },
        ["bar5"] = {
            ["buttonSize"] = 47,
            ["buttonSpacing"] = 5,
            ["buttons"] = 12,
            ["buttonsPerRow"] = 12,
            ["countFont"] = "Expressway",
            ["countFontOutline"] = "NONE",
            ["countFontSize"] = 11,
            ["hotkeyFont"] = "Expressway",
            ["hotkeyFontOutline"] = "NONE",
            ["hotkeyFontSize"] = 11,
            ["hotkeyTextXOffset"] = -2,
            ["macroFont"] = "Expressway",
            ["macroFontOutline"] = "NONE",
            ["macroFontSize"] = 11,
        },
        ["bar6"] = {
            ["buttonSize"] = 47,
            ["buttonSpacing"] = 5,
            ["countFont"] = "Expressway",
            ["countFontOutline"] = "NONE",
            ["countFontSize"] = 11,
            ["enabled"] = true,
            ["hotkeyFont"] = "Expressway",
            ["hotkeyFontOutline"] = "NONE",
            ["hotkeyFontSize"] = 11,
            ["hotkeyTextXOffset"] = -2,
            ["macroFont"] = "Expressway",
            ["macroFontOutline"] = "NONE",
            ["macroFontSize"] = 11,
        },
        ["bar7"] = {
            ["countFont"] = "Expressway",
            ["countFontOutline"] = "NONE",
            ["countFontSize"] = 11,
            ["hotkeyFont"] = "Expressway",
            ["hotkeyFontOutline"] = "NONE",
            ["hotkeyFontSize"] = 11,
            ["hotkeyTextXOffset"] = -2,
            ["macroFont"] = "Expressway",
            ["macroFontOutline"] = "NONE",
            ["macroFontSize"] = 11,
        },
        ["bar8"] = {
            ["countFont"] = "Expressway",
            ["countFontOutline"] = "NONE",
            ["countFontSize"] = 11,
            ["hotkeyFont"] = "Expressway",
            ["hotkeyFontOutline"] = "NONE",
            ["hotkeyFontSize"] = 11,
            ["hotkeyTextXOffset"] = -2,
            ["macroFont"] = "Expressway",
            ["macroFontOutline"] = "NONE",
            ["macroFontSize"] = 11,
        },
        ["bar9"] = {
            ["countFont"] = "Expressway",
            ["countFontOutline"] = "NONE",
            ["countFontSize"] = 11,
            ["hotkeyFont"] = "Expressway",
            ["hotkeyFontOutline"] = "NONE",
            ["hotkeyFontSize"] = 11,
            ["hotkeyTextXOffset"] = -2,
            ["macroFont"] = "Expressway",
            ["macroFontOutline"] = "NONE",
            ["macroFontSize"] = 11,
        },
        ["barPet"] = {
            ["backdrop"] = false,
            ["buttonHeight"] = 40,
            ["buttonSize"] = 47,
            ["buttonSpacing"] = 8,
            ["buttons"] = 9,
            ["buttonsPerRow"] = 3,
            ["countFont"] = "Expressway",
            ["countFontOutline"] = "NONE",
            ["countFontSize"] = 11,
            ["hotkeyFont"] = "Expressway",
            ["hotkeyFontOutline"] = "NONE",
            ["hotkeyFontSize"] = 11,
            ["hotkeyTextXOffset"] = -2,
        },
        ["cooldown"] = {
            ["fonts"] = {
                ["enable"] = true,
                ["font"] = "Expressway",
                ["fontSize"] = 15,
            },
        },
        ["extraActionButton"] = {
            ["hotkeyFont"] = "Expressway",
            ["hotkeyFontOutline"] = "NONE",
            ["hotkeyFontSize"] = 11,
            ["hotkeyTextXOffset"] = -2,
        },
        ["font"] = "Expressway",
        ["fontOutline"] = "NONE",
        ["fontSize"] = 11,
        ["microbar"] = {
            ["enabled"] = true,
            ["mouseover"] = true,
        },
        ["stanceBar"] = {
            ["buttonSize"] = 47,
            ["buttonSpacing"] = 8,
            ["buttons"] = 9,
            ["buttonsPerRow"] = 3,
            ["hotkeyFont"] = "Expressway",
            ["hotkeyFontOutline"] = "NONE",
            ["hotkeyFontSize"] = 11,
            ["hotkeyTextXOffset"] = -2,
            ["point"] = "TOPRIGHT",
        },
        ["useDrawSwipeOnCharges"] = true,
        ["vehicleExitButton"] = {
            ["hotkeyFont"] = "Expressway",
            ["hotkeyFontOutline"] = "NONE",
            ["hotkeyFontSize"] = 11,
            ["hotkeyTextXOffset"] = -2,
        },
    },
    ["auras"] = {
        ["buffs"] = {
            ["countFont"] = "Expressway",
            ["countFontSize"] = 13,
            ["horizontalSpacing"] = 5,
            ["timeFont"] = "Expressway",
            ["timeFontOutline"] = "OUTLINE",
            ["timeFontSize"] = 13,
            ["verticalSpacing"] = 18,
        },
        ["debuffs"] = {
            ["countFont"] = "Expressway",
            ["countFontSize"] = 13,
            ["horizontalSpacing"] = 5,
            ["maxWraps"] = 3,
            ["timeFont"] = "Expressway",
            ["timeFontOutline"] = "OUTLINE",
            ["timeFontSize"] = 13,
            ["verticalSpacing"] = 18,
        },
    },
    ["bags"] = {
        ["bagSize"] = 35,
        ["bagWidth"] = 460,
        ["clearSearchOnClose"] = true,
        ["countFont"] = "Expressway",
        ["countFontOutline"] = "OUTLINE",
        ["countFontSize"] = 13,
        ["itemLevelFont"] = "Expressway",
        ["itemLevelFontOutline"] = "OUTLINE",
        ["itemLevelFontSize"] = 13,
        ["junkIcon"] = true,
    },
    ["chat"] = {
        ["fade"] = false,
        ["font"] = "Expressway",
        ["fontSize"] = 13,
        ["hideChatToggles"] = true,
        ["panelHeight"] = 200,
        ["panelHeightRight"] = 250,
        ["panelTabBackdrop"] = true,
        ["panelTabTransparency"] = true,
        ["panelWidth"] = 460,
        ["panelWidthRight"] = 460,
        ["separateSizes"] = true,
        ["tabFont"] = "Expressway",
        ["tabFontSize"] = 13,
        ["tabSelector"] = "NONE",
        ["timeStampFormat"] = "%H:%M ",
    },
    ["convertPages"] = true,
    ["cooldown"] = {
        ["fonts"] = {
            ["enable"] = true,
            ["font"] = "Expressway",
        },
    },
    ["databars"] = {
        ["azerite"] = {
            ["enable"] = false,
            ["orientation"] = "HORIZONTAL",
            ["width"] = 536,
        },
        ["colors"] = {
            ["quest"] = {
                ["a"] = 1,
                ["b"] = 0.13725490196078,
                ["g"] = 0.5921568627451,
                ["r"] = 0.84313725490196,
            },
        },
        ["experience"] = {
            ["orientation"] = "HORIZONTAL",
            ["width"] = 460,
        },
        ["honor"] = {
            ["enable"] = false,
        },
        ["reputation"] = {
            ["orientation"] = "HORIZONTAL",
            ["width"] = 536,
        },
        ["threat"] = {
            ["enable"] = false,
        },
    },
    ["datatexts"] = {
        ["font"] = "Expressway",
        ["fontSize"] = 13,
        ["panels"] = {
            ["LeftChatDataPanel"] = {
                [1] = "Friends",
                [2] = "Guild",
                [3] = "System",
                ["left"] = "Friends",
                ["middle"] = "Guild",
                ["right"] = "System",
            },
            ["LeftMiniPanel"] = "Coords",
            ["MinimapPanel"] = {
                [1] = "Time",
                [2] = "Coords",
            },
            ["RightChatDataPanel"] = {
                [1] = "Durability",
                [2] = "Item Level",
                [3] = "Currencies",
                ["left"] = "Bags",
                ["middle"] = "Durability",
            },
            ["RightMiniPanel"] = "Time",
        },
    },
    ["general"] = {
        ["altPowerBar"] = {
            ["font"] = "Expressway",
        },
        ["bottomPanel"] = false,
        ["customGlow"] = {
            ["style"] = "Action Button Glow",
        },
        ["font"] = "Expressway",
        ["fontSize"] = 13,
        ["itemLevel"] = {
            ["itemLevelFont"] = "Expressway",
        },
        ["loginmessage"] = false,
        ["minimap"] = {
            ["locationFont"] = "Expressway",
            ["locationFontOutline"] = "NONE",
            ["locationText"] = "SHOW",
            ["size"] = 238,
        },
        ["talkingHeadFrameBackdrop"] = true,
        ["totems"] = {
            ["growthDirection"] = "HORIZONTAL",
            ["size"] = 47,
            ["spacing"] = 5,
        },
        ["valuecolor"] = {
            ["b"] = 0.77647058823529,
            ["g"] = 0.83137254901961,
            ["r"] = 0.54117647058824,
        },
    },
    ["movers"] = {
        ["AlertFrameMover"] = "TOP,UIParent,TOP,0,-121",
        ["ArenaHeaderMover"] = "TOPLEFT,UIParent,TOPLEFT,30,-55",
        ["ArtifactBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,13",
        ["AzeriteBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,0,205",
        ["BNETMover"] = "BOTTOMLEFT,UIParent,BOTTOMLEFT,30,271",
        ["BelowMinimapContainerMover"] = "TOP,UIParent,TOP,342,-361",
        ["BossButton"] = "BOTTOM,ElvUIParent,BOTTOM,0,440",
        ["BossHeaderMover"] = "TOP,ElvUIParent,TOP,0,-55",
        ["BuffsMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-280,-30",
        ["ClassBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,-276,213",
        ["DebuffsMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-280,-30",
        ["DigSiteProgressBarMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,423,50",
        ["DurabilityFrameMover"] = "TOP,UIParent,TOP,228,-253",
        ["ElvAB_1"] = "BOTTOM,ElvUIParent,BOTTOM,0,30",
        ["ElvAB_3"] = "TOPLEFT,ElvUIParent,TOPLEFT,432,-87",
        ["ElvAB_5"] = "BOTTOM,ElvUIParent,BOTTOM,0,138",
        ["ElvAB_6"] = "BOTTOM,ElvUIParent,BOTTOM,0,84",
        ["ElvUF_AssistMover"] = "TOPLEFT,UIParent,TOPLEFT,604,-297",
        ["ElvUF_FocusCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,212,279",
        ["ElvUF_FocusMover"] = "BOTTOM,ElvUIParent,BOTTOM,265,275",
        ["ElvUF_PartyMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,30,-30",
        ["ElvUF_PetCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,-394,200",
        ["ElvUF_PetMover"] = "BOTTOM,ElvUIParent,BOTTOM,-394,212",
        ["ElvUF_PlayerCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,-154,200",
        ["ElvUF_PlayerMover"] = "BOTTOM,ElvUIParent,BOTTOM,-154,212",
        ["ElvUF_Raid40Mover"] = "TOPLEFT,ElvUIParent,TOPLEFT,30,-30",
        ["ElvUF_RaidMover"] = "TOPLEFT,ElvUIParent,TOPLEFT,30,-30",
        ["ElvUF_RaidpetMover"] = "TOPLEFT,ElvUIParent,BOTTOMLEFT,4,736",
        ["ElvUF_TankMover"] = "TOPLEFT,UIParent,TOPLEFT,604,-362",
        ["ElvUF_TargetCastbarMover"] = "BOTTOM,ElvUIParent,BOTTOM,155,200",
        ["ElvUF_TargetMover"] = "BOTTOM,ElvUIParent,BOTTOM,155,212",
        ["ElvUF_TargetTargetMover"] = "BOTTOM,UIParent,BOTTOM,394,213",
        ["ElvUIBagMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-30,312",
        ["ElvUIBankMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-498,312",
        ["ExperienceBarMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,30,253",
        ["GMMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,30,271",
        ["HonorBarMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-410,479",
        ["LeftChatMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,30,31",
        ["LevelUpBossBannerMover"] = "TOP,ElvUIParent,TOP,0,-530",
        ["LossControlMover"] = "TOP,UIParent,TOP,0,-143",
        ["MawBuffsBelowMinimapMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-280,-56",
        ["MicrobarMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-30,-1",
        ["MinimapMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-30,-30",
        ["MirrorTimer3Mover"] = "TOP,ElvUIParent,TOP,0,-132",
        ["ObjectiveFrameMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-81,-332",
        ["PetAB"] = "BOTTOM,UIParent,BOTTOM,-394,30",
        ["ReputationBarMover"] = "BOTTOM,ElvUIParent,BOTTOM,-1,189",
        ["RightChatMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-30,30",
        ["ShiftAB"] = "BOTTOM,ElvUIParent,BOTTOM,-394,30",
        ["SocialMenuMover"] = "BOTTOMLEFT,ElvUIParent,BOTTOMLEFT,493,31",
        ["TalkingHeadFrameMover"] = "BOTTOM,UIParent,BOTTOM,0,330",
        ["ThreatBarMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-408,435",
        ["TooltipMover"] = "TOPRIGHT,ElvUIParent,TOPRIGHT,-280,-271",
        ["TotemBarMover"] = "BOTTOMRIGHT,ElvUIParent,BOTTOMRIGHT,-698,26",
        ["VOICECHAT"] = "BOTTOMLEFT,UIParent,BOTTOMLEFT,30,271",
        ["VehicleLeaveButton"] = "BOTTOM,UIParent,BOTTOM,403,404",
        ["VehicleSeatMover"] = "TOPRIGHT,UIParent,TOPRIGHT,-280,-164",
        ["ZoneAbility"] = "BOTTOM,ElvUIParent,BOTTOM,0,350",
    },
    ["nameplates"] = {
        ["colors"] = {
            ["glowColor"] = {
                ["a"] = 0.50923311710358,
            },
        },
        ["font"] = "Expressway",
        ["smoothbars"] = true,
        ["statusbar"] = "Minimalist",
        ["units"] = {
            ["ENEMY_NPC"] = {
                ["castbar"] = {
                    ["font"] = "Expressway",
                    ["fontSize"] = 10,
                },
                ["eliteIcon"] = {
                    ["enable"] = true,
                    ["position"] = "CENTER",
                    ["size"] = 26,
                    ["xOffset"] = -90,
                    ["yOffset"] = 5,
                },
                ["health"] = {
                    ["text"] = {
                        ["font"] = "Expressway",
                        ["format"] = "",
                    },
                },
                ["level"] = {
                    ["font"] = "Expressway",
                    ["xOffset"] = 4,
                    ["yOffset"] = -8,
                },
                ["name"] = {
                    ["font"] = "Expressway",
                    ["xOffset"] = -1,
                    ["yOffset"] = -8,
                },
                ["questIcon"] = {
                    ["xOffset"] = -2,
                },
            },
            ["ENEMY_PLAYER"] = {
                ["buffs"] = {
                    ["maxDuration"] = 0,
                    ["priority"] = "Blacklist,RaidBuffsElvUI,blockNoDuration,PlayerBuffs,TurtleBuffs,CastByUnit",
                    ["yOffset"] = 0,
                },
                ["debuffs"] = {
                    ["priority"] = "Blacklist,Personal,CCDebuffs",
                },
                ["health"] = {
                    ["text"] = {
                        ["format"] = "",
                    },
                },
                ["level"] = {
                    ["font"] = "Expressway",
                    ["format"] = "[difficultycolor][level][shortclassification]",
                    ["position"] = "BOTTOMRIGHT",
                },
                ["name"] = {
                    ["format"] = "[name]",
                    ["yOffset"] = -12,
                },
            },
            ["FRIENDLY_NPC"] = {
                ["buffs"] = {
                    ["priority"] = "Blacklist,RaidBuffsElvUI,Dispellable,blockNoDuration,PlayerBuffs,TurtleBuffs,CastByUnit",
                },
                ["castbar"] = {
                    ["font"] = "Expressway",
                    ["fontSize"] = 10,
                },
                ["debuffs"] = {
                    ["priority"] = "Blacklist,Personal,CCDebuffs",
                },
                ["eliteIcon"] = {
                    ["enable"] = true,
                    ["position"] = "CENTER",
                    ["size"] = 26,
                    ["xOffset"] = -90,
                    ["yOffset"] = 5,
                },
                ["health"] = {
                    ["text"] = {
                        ["font"] = "Expressway",
                        ["format"] = "",
                    },
                },
                ["level"] = {
                    ["font"] = "Expressway",
                    ["xOffset"] = 6,
                    ["yOffset"] = -12,
                },
                ["name"] = {
                    ["font"] = "Expressway",
                    ["yOffset"] = -12,
                },
                ["questIcon"] = {
                    ["xOffset"] = -2,
                },
            },
            ["FRIENDLY_PLAYER"] = {
                ["enable"] = false,
            },
            ["TARGET"] = {
                ["arrow"] = "Arrow65",
                ["arrowScale"] = 0.75,
                ["arrowSpacing"] = 0,
                ["classpower"] = {
                    ["classColor"] = true,
                    ["enable"] = true,
                    ["width"] = 127,
                },
                ["glowStyle"] = "none",
            },
        },
    },
    ["tooltip"] = {
        ["colorAlpha"] = 1,
        ["cursorAnchor"] = true,
        ["font"] = "Expressway",
        ["headerFontSize"] = 13,
        ["healthBar"] = {
            ["font"] = "Expressway",
            ["fontOutline"] = "NONE",
            ["text"] = false,
        },
        ["smallTextFontSize"] = 13,
        ["textFontSize"] = 13,
    },
    ["unitframe"] = {
        ["colors"] = {
            ["auraBarBuff"] = {
                ["b"] = 0.59607714414597,
                ["g"] = 0.99999779462814,
                ["r"] = 0,
            },
            ["castClassColor"] = true,
            ["castColor"] = {
                ["b"] = 0.1,
                ["g"] = 0.1,
                ["r"] = 0.1,
            },
            ["frameGlow"] = {
                ["mouseoverGlow"] = {
                    ["texture"] = "ElvUI Norm",
                },
            },
            ["health"] = {
                ["b"] = 0.1,
                ["g"] = 0.1,
                ["r"] = 0.1,
            },
            ["healthclass"] = true,
            ["power"] = {
                ["MANA"] = {
                    ["b"] = 0.63137254901961,
                    ["g"] = 0.45098039215686,
                    ["r"] = 0.30980392156863,
                },
            },
        },
        ["font"] = "Expressway",
        ["fontOutline"] = "NONE",
        ["fontSize"] = 12,
        ["smartRaidFilter"] = false,
        ["smoothbars"] = true,
        ["statusbar"] = "Minimalist",
        ["units"] = {
            ["arena"] = {
                ["buffs"] = {
                    ["enable"] = false,
                    ["maxDuration"] = 0,
                    ["priority"] = "Blacklist,CastByUnit,Dispellable,Whitelist,RaidBuffsElvUI",
                    ["sizeOverride"] = 22,
                    ["yOffset"] = 20,
                },
                ["castbar"] = {
                    ["overlayOnFrame"] = "Power",
                    ["width"] = 215,
                },
                ["customTexts"] = {
                    ["health-large"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 12,
                        ["text_format"] = "[health:percent:hidedead]",
                        ["xOffset"] = -4,
                        ["yOffset"] = 1,
                    },
                    ["health-percent"] = {
                        ["attachTextTo"] = "Power",
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 12,
                        ["text_format"] = "[level] [classification] [npctitle]",
                        ["xOffset"] = 4,
                        ["yOffset"] = 1,
                    },
                    ["name-large"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 13,
                        ["text_format"] = "[name]",
                        ["xOffset"] = 4,
                        ["yOffset"] = 1,
                    },
                    ["power-tihng"] = {
                        ["attachTextTo"] = "Power",
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 12,
                        ["text_format"] = "[curpp]/[maxpp]",
                        ["xOffset"] = -4,
                        ["yOffset"] = 0,
                    },
                },
                ["debuffs"] = {
                    ["desaturate"] = true,
                    ["enable"] = false,
                    ["maxDuration"] = 0,
                    ["priority"] = "Blacklist,Boss,Personal,RaidDebuffs,CastByUnit,Whitelist",
                    ["sizeOverride"] = 22,
                    ["yOffset"] = -3,
                },
                ["health"] = {
                    ["text_format"] = "",
                },
                ["height"] = 60,
                ["infoPanel"] = {
                    ["height"] = 16,
                },
                ["name"] = {
                    ["text_format"] = "",
                },
                ["orientation"] = "LEFT",
                ["portrait"] = {
                    ["style"] = "2D",
                    ["width"] = 60,
                },
                ["power"] = {
                    ["height"] = 30,
                    ["text_format"] = "",
                },
                ["pvpTrinket"] = {
                    ["enable"] = false,
                },
                ["spacing"] = 10,
                ["width"] = 250,
            },
            ["boss"] = {
                ["buffs"] = {
                    ["enable"] = false,
                },
                ["castbar"] = {
                    ["overlayOnFrame"] = "Power",
                },
                ["customTexts"] = {
                    ["health-large"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 12,
                        ["text_format"] = "[health:percent:hidedead]",
                        ["xOffset"] = -4,
                        ["yOffset"] = 1,
                    },
                    ["health-percent"] = {
                        ["attachTextTo"] = "Power",
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 12,
                        ["text_format"] = "[level] [classification] [npctitle]",
                        ["xOffset"] = 4,
                        ["yOffset"] = 1,
                    },
                    ["name-large"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 13,
                        ["text_format"] = "[name:custom:abbreviate]",
                        ["xOffset"] = 4,
                        ["yOffset"] = 1,
                    },
                },
                ["debuffs"] = {
                    ["enable"] = false,
                },
                ["growthDirection"] = "RIGHT",
                ["health"] = {
                    ["text_format"] = "",
                },
                ["height"] = 60,
                ["name"] = {
                    ["text_format"] = "",
                },
                ["orientation"] = "MIDDLE",
                ["portrait"] = {
                    ["enable"] = true,
                    ["width"] = 60,
                },
                ["power"] = {
                    ["height"] = 30,
                    ["text_format"] = "",
                },
                ["spacing"] = 10,
                ["threatStyle"] = "GLOW",
                ["width"] = 250,
            },
            ["focus"] = {
                ["enable"] = false,
            },
            ["party"] = {
                ["buffs"] = {
                    ["anchorPoint"] = "BOTTOMLEFT",
                    ["clickThrough"] = true,
                    ["countFont"] = "Expressway",
                    ["enable"] = true,
                    ["perrow"] = 5,
                    ["sizeOverride"] = 20,
                    ["spacing"] = 4,
                    ["yOffset"] = -6,
                },
                ["customTexts"] = {
                    ["[health:current]"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 12,
                        ["text_format"] = "[health:percent]",
                        ["xOffset"] = -20,
                        ["yOffset"] = 1,
                    },
                    ["[name]"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 13,
                        ["text_format"] = "[name:medium]",
                        ["xOffset"] = 5,
                        ["yOffset"] = 1,
                    },
                    ["level"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = false,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 12,
                        ["text_format"] = "[level]",
                        ["xOffset"] = -219,
                        ["yOffset"] = 13,
                    },
                    ["power-percentage"] = {
                        ["attachTextTo"] = "Power",
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 11,
                        ["text_format"] = "[curpp]/[maxpp]",
                        ["xOffset"] = -5,
                        ["yOffset"] = 1,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "BOTTOMRIGHT",
                    ["countFont"] = "Expressway",
                    ["growthX"] = "LEFT",
                    ["sizeOverride"] = 20,
                    ["spacing"] = 4,
                    ["yOffset"] = -6,
                },
                ["disableMouseoverGlow"] = true,
                ["fader"] = {
                    ["enable"] = false,
                },
                ["growthDirection"] = "DOWN_RIGHT",
                ["health"] = {
                    ["text_format"] = "",
                },
                ["height"] = 50,
                ["name"] = {
                    ["text_format"] = "",
                },
                ["portrait"] = {
                    ["enable"] = true,
                    ["style"] = "2D",
                    ["width"] = 50,
                },
                ["power"] = {
                    ["attachTextTo"] = "Power",
                    ["height"] = 25,
                    ["position"] = "LEFT",
                    ["text_format"] = "[perpp]%",
                    ["xOffset"] = 5,
                    ["yOffset"] = 1,
                },
                ["raidRoleIcons"] = {
                    ["position"] = "RIGHT",
                    ["xOffset"] = -31,
                    ["yOffset"] = 7,
                },
                ["rdebuffs"] = {
                    ["enable"] = false,
                    ["font"] = "Expressway",
                },
                ["readycheckIcon"] = {
                    ["attachTo"] = "CENTER",
                    ["enable"] = false,
                },
                ["roleIcon"] = {
                    ["position"] = "RIGHT",
                    ["size"] = 17,
                    ["xOffset"] = -3,
                    ["yOffset"] = 0,
                },
                ["verticalSpacing"] = 36,
                ["width"] = 250,
            },
            ["pet"] = {
                ["aurabar"] = {
                    ["attachTo"] = "DEBUFFS",
                    ["detachedWidth"] = 270,
                    ["priority"] = "Blacklist,blockNoDuration,Personal,Boss,RaidDebuffs,PlayerBuffs",
                    ["spacing"] = 0,
                    ["yOffset"] = 0,
                },
                ["buffs"] = {
                    ["anchorPoint"] = "TOPLEFT",
                    ["countFont"] = "Expressway",
                    ["maxDuration"] = 0,
                    ["perrow"] = 3,
                    ["priority"] = "Blacklist,Personal,PlayerBuffs,Whitelist,blockNoDuration,nonPersonal",
                    ["sizeOverride"] = 26,
                    ["spacing"] = 4,
                    ["yOffset"] = 5,
                },
                ["castbar"] = {
                    ["customTextFont"] = {
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontSize"] = 11,
                        ["fontStyle"] = "NONE",
                    },
                    ["customTimeFont"] = {
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontSize"] = 10,
                        ["fontStyle"] = "NONE",
                    },
                    ["height"] = 15,
                    ["width"] = 162,
                    ["xOffsetText"] = 3,
                    ["yOffsetText"] = 1,
                },
                ["customTexts"] = {
                    ["health-large"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = false,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 13,
                        ["text_format"] = "[perhp]%",
                        ["xOffset"] = -4,
                        ["yOffset"] = 1,
                    },
                    ["health-percent-large"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = false,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 12,
                        ["text_format"] = "[health:percent:hidedead]",
                        ["xOffset"] = -25,
                        ["yOffset"] = 12,
                    },
                    ["level"] = {
                        ["attachTextTo"] = "Power",
                        ["enable"] = false,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 14,
                        ["text_format"] = "[level] [classification] [npctitle]",
                        ["xOffset"] = 6,
                        ["yOffset"] = 0,
                    },
                    ["mob-health"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 13,
                        ["text_format"] = "[perhp]%",
                        ["xOffset"] = -6,
                        ["yOffset"] = 1,
                    },
                    ["pet-name"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 13,
                        ["text_format"] = "[name:custom:abbreviate:short]",
                        ["xOffset"] = 5,
                        ["yOffset"] = 1,
                    },
                    ["power-percentage"] = {
                        ["attachTextTo"] = "Power",
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 12,
                        ["text_format"] = "[curpp]/[maxpp]",
                        ["xOffset"] = -5,
                        ["yOffset"] = 1,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "TOPRIGHT",
                    ["attachTo"] = "BUFFS",
                    ["countFont"] = "Expressway",
                    ["growthX"] = "RIGHT",
                    ["maxDuration"] = 0,
                    ["perrow"] = 8,
                    ["priority"] = "Blacklist,Personal,nonPersonal",
                    ["sizeOverride"] = 26,
                    ["spacing"] = 3,
                    ["yOffset"] = 5,
                },
                ["disableMouseoverGlow"] = true,
                ["fader"] = {
                    ["casting"] = true,
                    ["combat"] = true,
                    ["enable"] = false,
                    ["hover"] = true,
                    ["minAlpha"] = 0,
                    ["playertarget"] = true,
                    ["power"] = true,
                    ["range"] = false,
                    ["unittarget"] = true,
                },
                ["health"] = {
                    ["position"] = "LEFT",
                    ["xOffset"] = 4,
                    ["yOffset"] = -4,
                },
                ["height"] = 60,
                ["infoPanel"] = {
                    ["height"] = 20,
                },
                ["name"] = {
                    ["attachTextTo"] = "Frame",
                    ["position"] = "LEFT",
                    ["text_format"] = "",
                    ["yOffset"] = 4,
                },
                ["orientation"] = "LEFT",
                ["portrait"] = {
                    ["style"] = "2D",
                    ["width"] = 60,
                },
                ["power"] = {
                    ["attachTextTo"] = "Power",
                    ["height"] = 30,
                    ["text_format"] = "[perpp]%",
                    ["xOffset"] = 6,
                    ["yOffset"] = 1,
                },
                ["threatStyle"] = "NONE",
                ["width"] = 160,
            },
            ["player"] = {
                ["CombatIcon"] = {
                    ["enable"] = false,
                },
                ["RestIcon"] = {
                    ["anchorPoint"] = "CENTER",
                    ["size"] = 25,
                    ["texture"] = "RESTING1",
                    ["xOffset"] = -19,
                    ["yOffset"] = 18,
                },
                ["aurabar"] = {
                    ["enable"] = false,
                },
                ["buffs"] = {
                    ["attachTo"] = "FRAME",
                    ["countFont"] = "Expressway",
                    ["countYOffset"] = -2,
                    ["enable"] = true,
                    ["numrows"] = 2,
                    ["perrow"] = 5,
                    ["priority"] = "Blacklist,Personal,PlayerBuffs,Whitelist,nonPersonal",
                    ["sizeOverride"] = 26,
                    ["spacing"] = 4,
                    ["xOffset"] = -1,
                    ["yOffset"] = 5,
                },
                ["castbar"] = {
                    ["customTextFont"] = {
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontSize"] = 11,
                        ["fontStyle"] = "NONE",
                    },
                    ["customTimeFont"] = {
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontSize"] = 10,
                        ["fontStyle"] = "NONE",
                    },
                    ["height"] = 15,
                    ["textColor"] = {
                        ["b"] = 1,
                        ["g"] = 1,
                        ["r"] = 1,
                    },
                    ["width"] = 306,
                    ["xOffsetText"] = 3,
                    ["xOffsetTime"] = -3,
                    ["yOffsetText"] = 1,
                    ["yOffsetTime"] = 1,
                },
                ["classbar"] = {
                    ["autoHide"] = true,
                    ["detachFromFrame"] = true,
                    ["detachedWidth"] = 60,
                    ["strataAndLevel"] = {
                        ["frameLevel"] = 2,
                    },
                },
                ["customTexts"] = {
                    ["health-large"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 13,
                        ["text_format"] = "[health:current:shortvalue]/[health:max:shortvalue]",
                        ["xOffset"] = -4,
                        ["yOffset"] = 1,
                    },
                    ["name-large"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 13,
                        ["text_format"] = "[name]",
                        ["xOffset"] = 6,
                        ["yOffset"] = 1,
                    },
                    ["power-percentage"] = {
                        ["attachTextTo"] = "Power",
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 12,
                        ["text_format"] = "[curpp]/[maxpp]",
                        ["xOffset"] = -5,
                        ["yOffset"] = 1,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "TOPRIGHT",
                    ["countFont"] = "Expressway",
                    ["growthX"] = "LEFT",
                    ["numrows"] = 2,
                    ["perrow"] = 5,
                    ["sizeOverride"] = 26,
                    ["spacing"] = 4,
                    ["xOffset"] = -1,
                    ["yOffset"] = 5,
                },
                ["disableMouseoverGlow"] = true,
                ["fader"] = {
                    ["minAlpha"] = 0,
                    ["smooth"] = 0,
                },
                ["health"] = {
                    ["text_format"] = "",
                    ["xOffset"] = 4,
                    ["yOffset"] = -4,
                },
                ["height"] = 60,
                ["infoPanel"] = {
                    ["height"] = 15,
                    ["transparent"] = true,
                },
                ["name"] = {
                    ["attachTextTo"] = "Frame",
                    ["position"] = "LEFT",
                    ["yOffset"] = 4,
                },
                ["partyIndicator"] = {
                    ["anchorPoint"] = "CENTER",
                    ["xOffset"] = -19,
                    ["yOffset"] = 18,
                },
                ["portrait"] = {
                    ["enable"] = true,
                    ["style"] = "2D",
                    ["width"] = 60,
                },
                ["power"] = {
                    ["attachTextTo"] = "Power",
                    ["height"] = 30,
                    ["position"] = "LEFT",
                    ["text_format"] = "[perpp]%",
                    ["xOffset"] = 5,
                    ["yOffset"] = 1,
                },
                ["raidRoleIcons"] = {
                    ["xOffset"] = 2,
                    ["yOffset"] = -9,
                },
                ["raidicon"] = {
                    ["size"] = 20,
                    ["xOffset"] = 30,
                    ["yOffset"] = 10,
                },
                ["width"] = 304,
            },
            ["raid"] = {
                ["buffs"] = {
                    ["anchorPoint"] = "RIGHT",
                    ["clickThrough"] = true,
                    ["countFont"] = "Expressway",
                    ["perrow"] = 8,
                    ["sizeOverride"] = 22,
                    ["xOffset"] = 5,
                    ["yOffset"] = 14,
                },
                ["customTexts"] = {
                    ["[health:current]"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = false,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 11,
                        ["text_format"] = "[health:percent]",
                        ["xOffset"] = -20,
                        ["yOffset"] = 1,
                    },
                    ["[name]"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 13,
                        ["text_format"] = "[name:medium]",
                        ["xOffset"] = 5,
                        ["yOffset"] = 1,
                    },
                    ["health-large"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = false,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 16,
                        ["text_format"] = "[health:current]",
                        ["xOffset"] = 0,
                        ["yOffset"] = -18,
                    },
                    ["level"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = false,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 12,
                        ["text_format"] = "[level]",
                        ["xOffset"] = -219,
                        ["yOffset"] = 13,
                    },
                    ["name-large"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = false,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 12,
                        ["text_format"] = "[name:medium]",
                        ["xOffset"] = 0,
                        ["yOffset"] = 11,
                    },
                    ["power-percentage"] = {
                        ["attachTextTo"] = "Power",
                        ["enable"] = false,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 11,
                        ["text_format"] = "[curpp]/[maxpp]",
                        ["xOffset"] = -5,
                        ["yOffset"] = 0,
                    },
                },
                ["debuffs"] = {
                    ["countFont"] = "Expressway",
                    ["perrow"] = 5,
                    ["sizeOverride"] = 22,
                    ["xOffset"] = 5,
                    ["yOffset"] = -14,
                },
                ["disableMouseoverGlow"] = true,
                ["fader"] = {
                    ["enable"] = false,
                },
                ["groupBy"] = "INDEX",
                ["groupSpacing"] = 20,
                ["groupsPerRowCol"] = 4,
                ["growthDirection"] = "DOWN_RIGHT",
                ["health"] = {
                    ["position"] = "LEFT",
                    ["text_format"] = "",
                    ["yOffset"] = 0,
                },
                ["height"] = 36,
                ["horizontalSpacing"] = 8,
                ["infoPanel"] = {
                    ["height"] = 15,
                },
                ["name"] = {
                    ["text_format"] = "",
                },
                ["numGroups"] = 8,
                ["orientation"] = "LEFT",
                ["portrait"] = {
                    ["style"] = "2D",
                    ["width"] = 50,
                },
                ["power"] = {
                    ["attachTextTo"] = "Power",
                    ["height"] = 10,
                    ["position"] = "LEFT",
                    ["xOffset"] = 5,
                    ["yOffset"] = 0,
                },
                ["raidRoleIcons"] = {
                    ["position"] = "RIGHT",
                    ["xOffset"] = 8,
                    ["yOffset"] = 2,
                },
                ["rdebuffs"] = {
                    ["enable"] = false,
                    ["font"] = "Expressway",
                },
                ["readycheckIcon"] = {
                    ["attachTo"] = "CENTER",
                    ["enable"] = false,
                },
                ["roleIcon"] = {
                    ["position"] = "RIGHT",
                    ["size"] = 17,
                    ["xOffset"] = -3,
                    ["yOffset"] = 0,
                },
                ["verticalSpacing"] = 8,
                ["width"] = 160,
            },
            ["raid40"] = {
                ["buffs"] = {
                    ["anchorPoint"] = "RIGHT",
                    ["clickThrough"] = true,
                    ["perrow"] = 8,
                    ["sizeOverride"] = 22,
                    ["xOffset"] = 5,
                    ["yOffset"] = 14,
                },
                ["customTexts"] = {
                    ["health-large"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 16,
                        ["text_format"] = "[health:current]",
                        ["xOffset"] = 0,
                        ["yOffset"] = -18,
                    },
                    ["name-large"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "OUTLINE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 12,
                        ["text_format"] = "[name:medium]",
                        ["xOffset"] = 0,
                        ["yOffset"] = 11,
                    },
                },
                ["debuffs"] = {
                    ["perrow"] = 8,
                    ["sizeOverride"] = 22,
                    ["xOffset"] = 5,
                    ["yOffset"] = -14,
                },
                ["disableMouseoverGlow"] = true,
                ["groupBy"] = "ROLE",
                ["groupSpacing"] = 1,
                ["growthDirection"] = "UP_LEFT",
                ["health"] = {
                    ["position"] = "LEFT",
                    ["text_format"] = "",
                    ["yOffset"] = 0,
                },
                ["height"] = 50,
                ["horizontalSpacing"] = 8,
                ["infoPanel"] = {
                    ["height"] = 15,
                },
                ["name"] = {
                    ["text_format"] = "",
                },
                ["numGroups"] = 4,
                ["orientation"] = "LEFT",
                ["power"] = {
                    ["enable"] = true,
                    ["position"] = "RIGHT",
                    ["yOffset"] = 0,
                },
                ["rdebuffs"] = {
                    ["font"] = "Expressway",
                },
                ["roleIcon"] = {
                    ["damager"] = false,
                    ["enable"] = true,
                    ["position"] = "LEFT",
                    ["size"] = 16,
                    ["xOffset"] = 90,
                    ["yOffset"] = -11,
                },
                ["verticalSpacing"] = 8,
                ["width"] = 107,
            },
            ["target"] = {
                ["CombatIcon"] = {
                    ["enable"] = false,
                },
                ["aurabar"] = {
                    ["enable"] = false,
                },
                ["buffs"] = {
                    ["anchorPoint"] = "TOPLEFT",
                    ["countFont"] = "Expressway",
                    ["growthX"] = "RIGHT",
                    ["numrows"] = 2,
                    ["perrow"] = 5,
                    ["priority"] = "Blacklist,Personal,PlayerBuffs,Whitelist,nonPersonal",
                    ["sizeOverride"] = 26,
                    ["spacing"] = 4,
                    ["xOffset"] = -1,
                    ["yOffset"] = 5,
                },
                ["castbar"] = {
                    ["customTextFont"] = {
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontSize"] = 11,
                        ["fontStyle"] = "NONE",
                    },
                    ["customTimeFont"] = {
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontSize"] = 11,
                        ["fontStyle"] = "NONE",
                    },
                    ["height"] = 15,
                    ["textColor"] = {
                        ["b"] = 1,
                        ["g"] = 1,
                        ["r"] = 1,
                    },
                    ["width"] = 306,
                    ["xOffsetText"] = 5,
                    ["xOffsetTime"] = -5,
                },
                ["customTexts"] = {
                    ["health-large"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = false,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 13,
                        ["text_format"] = "[health:current]/[health:current-max]",
                        ["xOffset"] = -4,
                        ["yOffset"] = 1,
                    },
                    ["health-percent-large"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = false,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 12,
                        ["text_format"] = "[health:percent:hidedead]",
                        ["xOffset"] = -25,
                        ["yOffset"] = 12,
                    },
                    ["level"] = {
                        ["attachTextTo"] = "Power",
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 14,
                        ["text_format"] = "[level] [classification] [npctitle]",
                        ["xOffset"] = 6,
                        ["yOffset"] = 0,
                    },
                    ["mob-health"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 13,
                        ["text_format"] = "[health:current:shortvalue] [perhp]%",
                        ["xOffset"] = -6,
                        ["yOffset"] = 1,
                    },
                    ["name-large"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 13,
                        ["text_format"] = "[name:custom:abbreviate]",
                        ["xOffset"] = 6,
                        ["yOffset"] = 1,
                    },
                    ["power-percentage"] = {
                        ["attachTextTo"] = "Power",
                        ["enable"] = false,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 12,
                        ["text_format"] = "[curpp]/[maxpp]",
                        ["xOffset"] = -5,
                        ["yOffset"] = 1,
                    },
                },
                ["debuffs"] = {
                    ["attachTo"] = "FRAME",
                    ["countFont"] = "Expressway",
                    ["maxDuration"] = 0,
                    ["numrows"] = 2,
                    ["perrow"] = 5,
                    ["priority"] = "Blacklist,Personal,nonPersonal",
                    ["sizeOverride"] = 26,
                    ["spacing"] = 4,
                    ["xOffset"] = -1,
                    ["yOffset"] = 5,
                },
                ["fader"] = {
                    ["smooth"] = 0.1,
                },
                ["health"] = {
                    ["position"] = "LEFT",
                    ["text_format"] = "",
                    ["xOffset"] = 4,
                    ["yOffset"] = -4,
                },
                ["height"] = 60,
                ["infoPanel"] = {
                    ["transparent"] = true,
                },
                ["name"] = {
                    ["attachTextTo"] = "Frame",
                    ["position"] = "LEFT",
                    ["text_format"] = "",
                    ["yOffset"] = 4,
                },
                ["portrait"] = {
                    ["enable"] = true,
                    ["style"] = "2D",
                    ["width"] = 60,
                },
                ["power"] = {
                    ["attachTextTo"] = "Power",
                    ["height"] = 30,
                    ["text_format"] = "",
                    ["xOffset"] = 5,
                    ["yOffset"] = 1,
                },
                ["raidRoleIcons"] = {
                    ["position"] = "RIGHT",
                    ["xOffset"] = -2,
                    ["yOffset"] = 11,
                },
                ["raidicon"] = {
                    ["size"] = 20,
                    ["xOffset"] = -30,
                    ["yOffset"] = 10,
                },
                ["width"] = 304,
            },
            ["targettarget"] = {
                ["buffs"] = {
                    ["anchorPoint"] = "TOPLEFT",
                    ["countFont"] = "Expressway",
                    ["maxDuration"] = 0,
                    ["perrow"] = 8,
                    ["priority"] = "Blacklist,Personal,PlayerBuffs,Whitelist,blockNoDuration,nonPersonal",
                    ["sizeOverride"] = 26,
                    ["spacing"] = 3,
                    ["yOffset"] = 5,
                },
                ["customTexts"] = {
                    ["health-large"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 13,
                        ["text_format"] = "[perhp]%",
                        ["xOffset"] = -4,
                        ["yOffset"] = 1,
                    },
                    ["name-large"] = {
                        ["attachTextTo"] = "Health",
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "LEFT",
                        ["size"] = 13,
                        ["text_format"] = "[name:custom:abbreviate:short]",
                        ["xOffset"] = 6,
                        ["yOffset"] = 1,
                    },
                    ["power-percentage"] = {
                        ["attachTextTo"] = "Power",
                        ["enable"] = true,
                        ["font"] = "Expressway",
                        ["fontOutline"] = "NONE",
                        ["justifyH"] = "RIGHT",
                        ["size"] = 12,
                        ["text_format"] = "[curpp]/[maxpp]",
                        ["xOffset"] = -5,
                        ["yOffset"] = 1,
                    },
                },
                ["debuffs"] = {
                    ["anchorPoint"] = "TOPRIGHT",
                    ["countFont"] = "Expressway",
                    ["enable"] = false,
                    ["growthX"] = "RIGHT",
                    ["maxDuration"] = 0,
                    ["perrow"] = 8,
                    ["priority"] = "Blacklist,Personal,nonPersonal",
                    ["sizeOverride"] = 26,
                    ["spacing"] = 3,
                    ["yOffset"] = 5,
                },
                ["disableMouseoverGlow"] = true,
                ["fader"] = {
                    ["smooth"] = 0.2,
                },
                ["healPrediction"] = {
                    ["enable"] = true,
                },
                ["health"] = {
                    ["position"] = "LEFT",
                    ["xOffset"] = 4,
                    ["yOffset"] = -4,
                },
                ["height"] = 60,
                ["infoPanel"] = {
                    ["height"] = 20,
                },
                ["name"] = {
                    ["attachTextTo"] = "Frame",
                    ["position"] = "LEFT",
                    ["text_format"] = "",
                    ["yOffset"] = 4,
                },
                ["orientation"] = "LEFT",
                ["portrait"] = {
                    ["style"] = "2D",
                    ["width"] = 60,
                },
                ["power"] = {
                    ["attachTextTo"] = "Power",
                    ["height"] = 30,
                    ["text_format"] = "[perpp]%",
                    ["xOffset"] = 5,
                    ["yOffset"] = 1,
                },
                ["width"] = 160,
            },
        },
    },
}::profile::Vivify